/*
 * This file has been automatically generated by the WICED 20719-B1 Designer.
 * Definitions for constants used in the device's GATT database and function
 * prototypes.
 *
 */

// ESS_BLE_db.h

#ifndef __GATT_DATABASE_H__
#define __GATT_DATABASE_H__

#define __UUID_ESS_SERVICE                    0xd4, 0x6c, 0xac, 0x63, 0x53, 0xe8, 0x43, 0xac, 0x8b, 0x1f, 0xb5, 0xb5, 0x73, 0x84, 0xcc, 0x6b
#define __UUID_ESS_SERVICE_BUTTON             0x63, 0xaf, 0x77, 0xde, 0x1e, 0xcc, 0x47, 0xb4, 0xb4, 0xde, 0xeb, 0xa6, 0xbe, 0x15, 0x79, 0x21
#define __UUID_ESS_SERVICE_TEMPERATURE        0x57, 0x78, 0xa3, 0x0d, 0x97, 0x1b, 0x44, 0x5b, 0xbe, 0x14, 0x13, 0xe9, 0x2f, 0x6e, 0x16, 0x43
#define __UUID_ESS_SERVICE_HUMIDITY           0x2c, 0x09, 0x39, 0x21, 0x4b, 0xb0, 0x4b, 0xd5, 0xb2, 0x4a, 0x8d, 0x1d, 0x92, 0x08, 0x6c, 0xe9
#define __UUID_ESS_SERVICE_ECO2               0x4e, 0xe6, 0xa7, 0xd0, 0xe9, 0xe4, 0x42, 0xb4, 0xb9, 0xd5, 0xb2, 0x6c, 0xd9, 0x9f, 0xae, 0xd5
#define __UUID_ESS_SERVICE_TVOC               0x4d, 0xc5, 0x8b, 0xff, 0xec, 0xe4, 0x48, 0x93, 0xa6, 0x9a, 0x0f, 0x82, 0xeb, 0x4b, 0xc5, 0x6a


// ***** Primary Service 'Generic Attribute'
#define HDLS_GENERIC_ATTRIBUTE                0x0001

// ***** Primary Service 'Generic Access'
#define HDLS_GENERIC_ACCESS                   0x0014
// ----- Characteristic 'Device Name'
#define HDLC_GENERIC_ACCESS_DEVICE_NAME       0x0015
#define HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE 0x0016
// ----- Characteristic 'Appearance'
#define HDLC_GENERIC_ACCESS_APPEARANCE        0x0017
#define HDLC_GENERIC_ACCESS_APPEARANCE_VALUE  0x0018

// ***** Primary Service 'ESS_Service'
#define HDLS_ESS_SERVICE                      0x0028
// ----- Characteristic 'button'
#define HDLC_ESS_SERVICE_BUTTON               0x0029
#define HDLC_ESS_SERVICE_BUTTON_VALUE         0x002A
//------ Characteristic 'temperature'
#define HDLC_ESS_SERVICE_TEMPERATURE                      0x0030
#define HDLC_ESS_SERVICE_TEMPERATURE_VALUE                0x0031
#define HDLD_ESS_SERVICE_TEMPERATURE_USER_DESCRIPTION     0x0032
#define HDLD_ESS_SERVICE_TEMPERATURE_CLIENT_CONFIGURATION 0x0033
//------ Characteristic 'humidity'
#define HDLC_ESS_SERVICE_HUMIDITY                      0x0034
#define HDLC_ESS_SERVICE_HUMIDITY_VALUE                0x0035
#define HDLD_ESS_SERVICE_HUMIDITY_USER_DESCRIPTION     0x0036
#define HDLD_ESS_SERVICE_HUMIDITY_CLIENT_CONFIGURATION 0x0037
//------ Characteristic 'temperature'
#define HDLC_ESS_SERVICE_ECO2                      0x0038
#define HDLC_ESS_SERVICE_ECO2_VALUE                0x0039
#define HDLD_ESS_SERVICE_ECO2_USER_DESCRIPTION     0x003a
#define HDLD_ESS_SERVICE_ECO2_CLIENT_CONFIGURATION 0x003b
//------ Characteristic 'temperature'
#define HDLC_ESS_SERVICE_TVOC                      0x003c
#define HDLC_ESS_SERVICE_TVOC_VALUE                0x003d
#define HDLD_ESS_SERVICE_TVOC_USER_DESCRIPTION     0x003e
#define HDLD_ESS_SERVICE_TVOC_CLIENT_CONFIGURATION 0x003f

// External Lookup Table Entry
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table;

// External definitions
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table ess_ble_gatt_db_ext_attr_tbl[];
extern const uint16_t ess_ble_gatt_db_ext_attr_tbl_size;
extern uint8_t BT_LOCAL_NAME[];
extern const uint16_t BT_LOCAL_NAME_CAPACITY;

#endif /* __GATT_DATABASE_H__ */
