#
# This file has been automatically generated by the WICED 20719-B1 Designer.
#

APP_SRC = ESS_BLE.c
APP_SRC += ESS_BLE_db.c
APP_SRC += wiced_bt_cfg.c
APP_SRC += sensirion.c

C_FLAGS += -DWICED_BT_TRACE_ENABLE

# If defined, HCI traces are sent over transport/WICED HCI interface
C_FLAGS += -DHCI_TRACE_OVER_TRANSPORT

########################################################################
################ DO NOT MODIFY FILE BELOW THIS LINE ####################
########################################################################

